### ISSUE TITLE
Close button not working on articles

### ISSUE THREAD

**Issue by morgycatt** [modxcms/Articles#162]
Articles version 1.8.0, MODX ver 2.8.4
The close button on articles is not working.
The console log is showing the following when clicked.

Uncaught TypeError: Cannot read properties of undefined (reading 'formpanel')
    at MODx.Component.cancel (update.js:89:41)
    at S.onClick (ext-all.js:21:426947)
    at HTMLSpanElement.I (ext-all.js:21:57750)
cancel @ update.js:89
onClick @ ext-all.js:21
I @ ext-all.js:21

Then since this is not working, when clicking on the site tree to go away from the edit page, there is a message saying "Changes you have made may no be saved’" even though the article has been saved.

Is this a known bug?
Is there a temp code edit to fix before the next release of Articles?

many thanks

**Comment by rthrash** [comment]
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/articles-issues-with-upgrade/5340/9
